services:
  # Next.js web app for development with HMR
  web-dev:
    container_name: ${COMPOSE_PROJECT_NAME:-nextjs-nestjs}-web-dev
    build:
      context: .
      dockerfile: ./docker/Dockerfile.web.dev
      args:
        - NODE_ENV=development
        - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL:-http://localhost:3001}
        - API_PORT=${API_PORT:-3001}
        - NEXT_PUBLIC_APP_URL=${NEXT_PUBLIC_APP_URL:-http://localhost:3000}
        - NEXT_PUBLIC_APP_PORT=${NEXT_PUBLIC_APP_PORT:-3000}
        - API_PING_PATH=${API_PING_PATH:-/health}
        - API_ADMIN_TOKEN=${API_ADMIN_TOKEN:-secret-admin-token}
        - AUTH_SECRET=${AUTH_SECRET:-QgafJQw3O/k1gambz7YGKjtj5ZZe0dnL/WlSw4PtMDc=}
    restart: unless-stopped
    ports:
      - "${NEXT_PUBLIC_APP_PORT:-3000}:${NEXT_PUBLIC_APP_PORT:-3000}"
    volumes:
      # Mount source code for hot reloading
      - .:/app
      - /app/node_modules
      - /app/apps/web/node_modules
      - /app/apps/web/.next
      # Persistent caches
      - bun_cache_web_dev:/root/.bun/install/cache
      - turbo_cache_web_dev:/root/.cache/turbo
    environment:
      - NODE_ENV=development
      - API_PING_PATH=/health
      # Server-side API URL (external API server)
      - API_URL=${NEXT_PUBLIC_API_URL:-http://localhost:3001}
      # Client-side API URL (localhost for browser)
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL:-http://localhost:3001}
      - NEXT_PUBLIC_API_PORT=${API_PORT:-3001}
      - NEXT_PUBLIC_APP_URL=${NEXT_PUBLIC_APP_URL:-http://localhost:3000}
      - NEXT_PUBLIC_APP_PORT=${NEXT_PUBLIC_APP_PORT:-3000}
      - NEXT_PUBLIC_DOC_PORT=${NEXT_PUBLIC_DOC_PORT:-3020}
      - NEXT_PUBLIC_DOC_URL=http://localhost:${NEXT_PUBLIC_DOC_PORT:-3020}
      - API_ADMIN_TOKEN=${API_ADMIN_TOKEN:-secret-admin-token}
      - AUTH_SECRET=${AUTH_SECRET:-QgafJQw3O/k1gambz7YGKjtj5ZZe0dnL/WlSw4PtMDc=}
      # Debug configuration
      - NEXT_PUBLIC_DEBUG=${NEXT_PUBLIC_DEBUG}
      # Enable hot reloading
      - WATCHPACK_POLLING=true
      - CHOKIDAR_USEPOLLING=true
      # Development specific settings
      - NEXT_TELEMETRY_DISABLED=1
      - MILLION_LINT=false
      - REACT_SCAN=false
      - SHOW_AUTH_LOGS=true
      - NEXT_PUBLIC_SHOW_AUTH_LOGS=true
    # Use host networking to easily connect to external API
    network_mode: host

  # Docs app for development with HMR (standalone)
  doc-dev:
    container_name: ${COMPOSE_PROJECT_NAME:-nextjs-nestjs}-doc-dev
    build:
      context: .
      dockerfile: ./docker/Dockerfile.doc.dev
    restart: unless-stopped
    volumes:
      - .:/app
      - /app/node_modules
      - /app/apps/doc/node_modules
      - /app/apps/doc/.next
      - bun_cache_doc_dev:/root/.bun/install/cache
      - turbo_cache_doc_dev:/root/.cache/turbo
    environment:
      - NODE_ENV=development
      - WATCHPACK_POLLING=true
      - CHOKIDAR_USEPOLLING=true
    network_mode: host

volumes:
  bun_cache_web_dev:
    name: ${COMPOSE_PROJECT_NAME:-nextjs-nestjs}_bun_cache_web_dev
  turbo_cache_web_dev:
    name: ${COMPOSE_PROJECT_NAME:-nextjs-nestjs}_turbo_cache_web_dev
  bun_cache_doc_dev:
    name: ${COMPOSE_PROJECT_NAME:-nextjs-nestjs}_bun_cache_doc_dev
  turbo_cache_doc_dev:
    name: ${COMPOSE_PROJECT_NAME:-nextjs-nestjs}_turbo_cache_doc_dev
