import type { KnipConfig } from 'knip'

const config: KnipConfig = {
  // Workspaces to include
  workspaces: {
    '.': {
      entry: [
        'scripts/**/*.ts',
        'vitest.config.mts',
      ],
      project: ['**/*.ts', '**/*.tsx', '**/*.js', '**/*.jsx'],
    },
    'apps/api': {
      entry: [
        'src/main.ts',
        'src/entrypoint.prod.ts',
        'drizzle.config.ts',
        'debug-cli.ts',
        'scripts/**/*.ts',
        'vitest.config.mts',
      ],
      project: ['src/**/*.ts', 'scripts/**/*.ts'],
    },
    'apps/web': {
      entry: [
        'src/app/**/*.tsx',
        'src/app/**/*.ts',
        'src/middleware.ts',
        'next.config.ts',
        'env.ts',
        'scripts/**/*.ts',
        'vitest.config.mts',
      ],
      project: ['src/**/*.ts', 'src/**/*.tsx', 'scripts/**/*.ts'],
    },
    'apps/doc': {
      entry: [
        'src/app/**/*.tsx',
        'src/app/**/*.ts',
        'next.config.ts',
        'source.config.ts',
      ],
      project: ['src/**/*.ts', 'src/**/*.tsx', 'content/**/*.mdx'],
    },
    'packages/**': {
      entry: [
        'src/index.ts',
        'src/index.tsx',
        'vitest.config.ts',
        'vitest.config.mts',
      ],
      project: ['src/**/*.ts', 'src/**/*.tsx'],
    },
  },

  // Ignore patterns - files to exclude from analysis
  ignore: [
    // Build outputs
    '**/dist/**',
    '**/.next/**',
    '**/build/**',
    '**/coverage/**',
    '**/.turbo/**',
    
    // Node modules
    '**/node_modules/**',
    
    // Test files (Knip has special handling for these)
    '**/__tests__/**',
    '**/*.test.ts',
    '**/*.test.tsx',
    '**/*.spec.ts',
    '**/*.spec.tsx',
    
    // Config files that are used but not explicitly imported
    '**/.eslintrc.js',
    '**/eslint.config.ts',
    '**/prettier.config.js',
    '**/postcss.config.mjs',
    '**/tailwind.config.ts',
    '**/tailwind.config.mts',
    
    // Docker and CI files
    '**/Dockerfile*',
    '**/.dockerignore',
    '**/.github/**',
    
    // Environment and config
    '**/.env*',
    '**/tsconfig*.json',
    
    // Documentation
    '**/*.md',
    '**/AGENTS.md',
    
    // Generated files
    '**/apps/web/src/routes/index.ts', // Generated by declarative-routing
  ],

  // Ignore certain dependencies that are used but hard to detect
  ignoreDependencies: [
    // Runtime dependencies used in ways Knip can't detect
    '@types/node', // TypeScript types
    '@types/react',
    '@types/react-dom',
    
    // Build tools
    'typescript',
    'vite',
    'turbo',
    
    // Linting and formatting (used via CLI)
    'eslint',
    'prettier',
    
    // Docker and environment tools
    'dotenv-cli',
    'concurrently',
    'cross-env',
    'rimraf',
    
    // Testing framework (used via CLI)
    'vitest',
    '@vitest/ui',
    '@vitest/coverage-v8',
    'nyc',
    
    // Next.js peer dependencies
    'next',
    'react',
    'react-dom',
    
    // NestJS CLI tools
    '@nestjs/cli',
    '@nestjs/schematics',
    
    // PostCSS plugins (used via config)
    '@tailwindcss/postcss',
    'tailwindcss',
    
    // Scripts and CLI tools
    '@n0safe/envcli',
    '@n0safe/trycli',
    '@n0safe/rununtil',
  ],

  // Ignore binaries that are called but not in dependencies
  ignoreBinaries: [
    'docker',
    'docker-compose',
    'bun',
    'bunx',
    'sh',
  ],

  // Ignore exports from certain files (used by external tools)
  ignoreExportsUsedInFile: {
    interface: true,
    type: true,
  },

  // Plugin configurations
  next: {
    entry: [
      'next.config.ts',
      'src/middleware.ts',
      'src/app/**/*.tsx',
      'src/app/**/*.ts',
    ],
  },
  
  vitest: {
    entry: ['vitest.config.{ts,mts}', 'vitest.setup.ts'],
  },
}

export default config
