services:
  # NestJS API Service
  - type: web
    name: nestjs-api
    runtime: docker
    dockerfilePath: ./docker/Dockerfile.api.prod
    plan: free
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: API_PORT
        value: "3001"
      # Database Configuration
      - key: DB_HOST
        fromDatabase:
          name: nestjs-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: nestjs-db
          property: port
      - key: DB_DATABASE
        fromDatabase:
          name: nestjs-db
          property: database
      - key: DB_USER
        fromDatabase:
          name: nestjs-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: nestjs-db
          property: password
      # API Configuration
      - key: NEXT_PUBLIC_API_URL
        fromService:
          type: web
          name: nestjs-api
          envVarKey: RENDER_EXTERNAL_URL
      - key: API_PING_PATH
        value: /health
      - key: API_ADMIN_TOKEN
        generateValue: true
      # Authentication
      - key: AUTH_SECRET
        generateValue: true
      - key: JWT_SECRET
        generateValue: true
      # Web App URL for CORS
      - key: NEXT_PUBLIC_APP_URL
        fromService:
          type: web
          name: nextjs-web
          envVarKey: RENDER_EXTERNAL_URL

  # Next.js Web Service
  - type: web
    name: nextjs-web
    runtime: docker
    dockerfilePath: ./docker/Dockerfile.web.build-time.prod
    plan: free
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
      - key: NEXT_PUBLIC_APP_PORT
        value: "3000"
      # API Configuration
      - key: NEXT_PUBLIC_API_URL
        fromService:
          type: web
          name: nestjs-api
          envVarKey: RENDER_EXTERNAL_URL
      - key: API_URL
        fromService:
          type: web
          name: nestjs-api
          envVarKey: RENDER_EXTERNAL_URL
      # Web App Configuration
      - key: NEXT_PUBLIC_APP_URL
        fromService:
          type: web
          name: nextjs-web
          envVarKey: RENDER_EXTERNAL_URL
      # Documentation Site URL
      - key: NEXT_PUBLIC_DOC_URL
        fromService:
          type: web
          name: doc-app
          envVarKey: RENDER_EXTERNAL_URL
      # Authentication
      - key: AUTH_SECRET
        generateValue: true
      - key: API_ADMIN_TOKEN
        sync: false # Will be set manually to match API service
      # API Configuration
      - key: API_PING_PATH
        value: /health
      - key: NEXT_TELEMETRY_DISABLED
        value: "1"

  # Documentation Site Service  
  - type: web
    name: doc-app
    runtime: docker
    dockerfilePath: ./docker/Dockerfile.doc.build-time.prod
    plan: free
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
      - key: NEXT_PUBLIC_DOC_PORT
        value: "3020"

databases:
  - name: nestjs-db
    databaseName: nestjs_api
    user: nestjs_user
    plan: free
