/**
 * layout.info.ts - Auto-generated layout info file
 * 
 * This file is automatically generated by declarative-routing build system
 */

import { z } from 'zod'

// Export the Route info for makeLayout to use
export const DashboardLayoutRoute = {
  name: 'DashboardLayout',
  params: z.object({}),
  data: z.object({
    title: z.string(),
    requiresAuth: z.boolean(),
  }),
  innerState: z.object({
    sidebarOpen: z.boolean(),
    toggleSidebar: z.function(),
  })
}

export const HomeLayoutRoute = {
  name: 'HomeLayout',
  params: z.object({}),
  data: z.object({
    title: z.string(),
    requiresAuth: z.boolean(),
  }),
  innerState: z.object({
    theme: z.enum(['light', 'dark']),
    setTheme: z.function(),
  })
}

// Type exports for convenience
export type DashboardLayoutData = z.infer<typeof DashboardLayoutRoute.data>
export type DashboardLayoutInnerState = {
  sidebarOpen: boolean
  toggleSidebar: () => void
}

export type HomeLayoutData = z.infer<typeof HomeLayoutRoute.data>
export type HomeLayoutInnerState = {
  theme: 'light' | 'dark'
  setTheme: (theme: 'light' | 'dark') => void
}
