/**
 * routes/index.ts - Auto-generated routes and layouts
 * 
 * This file is automatically generated by: bun run web -- dr:build
 */

import { makeRoute, makeGetRoute, makePostRoute, makePutRoute, makeDeleteRoute } from './makeRoute'
import { makeLayout } from './makeLayout'

// ============================================================================
// LAYOUT IMPORTS
// ============================================================================

import { DashboardLayoutFn, DashboardLayoutRoute } from '@/app/dashboard/layout'
import { HomeLayoutFn, HomeLayoutRoute } from '@/app/layout'

// ============================================================================
// ROUTE IMPORTS (existing)
// ============================================================================

import { Route as HomeRoute } from '@/app/page.info'
import { Route as DashboardHomeRoute } from '@/app/dashboard/page.info'
import { Route as DashboardSettingsRoute } from '@/app/dashboard/settings/page.info'

// ============================================================================
// LAYOUTS (NEW)
// ============================================================================

/**
 * Dashboard Layout
 * Path: /dashboard
 * Usage: 
 *   - withLayout(DashboardLayout)(PageComponent)
 *   - useLayoutData(DashboardLayout)
 */
export const DashboardLayout = makeLayout('/dashboard', {
  name: 'DashboardLayout',
  params: DashboardLayoutRoute.params,
  data: DashboardLayoutRoute.data,
  innerState: DashboardLayoutRoute.innerState,
  layoutFn: DashboardLayoutFn
})

/**
 * Home Layout
 * Path: /
 * Usage:
 *   - withLayout(HomeLayout)(PageComponent)
 *   - useLayoutData(HomeLayout)
 */
export const HomeLayout = makeLayout('/', {
  name: 'HomeLayout',
  params: HomeLayoutRoute.params,
  data: HomeLayoutRoute.data,
  innerState: HomeLayoutRoute.innerState,
  layoutFn: HomeLayoutFn
})

// ============================================================================
// ROUTES (existing)
// ============================================================================

/**
 * Home Page
 * Path: /
 * Usage: <Home.Link>...</Home.Link>
 */
export const Home = makeRoute('/', {
  name: 'Home',
  params: HomeRoute.params,
  search: z.object({})
})

/**
 * Dashboard Home
 * Path: /dashboard
 * Usage: <DashboardHome.Link>...</DashboardHome.Link>
 */
export const DashboardHome = makeRoute('/dashboard', {
  name: 'DashboardHome',
  params: DashboardHomeRoute.params,
  search: z.object({})
})

/**
 * Dashboard Settings
 * Path: /dashboard/settings
 * Usage: <DashboardSettings.Link>...</DashboardSettings.Link>
 */
export const DashboardSettings = makeRoute('/dashboard/settings', {
  name: 'DashboardSettings',
  params: DashboardSettingsRoute.params,
  search: z.object({})
})

// ============================================================================
// TYPE EXPORTS
// ============================================================================

// Layout types
export type {
  DashboardLayoutData,
  DashboardLayoutInnerState,
  HomeLayoutData,
  HomeLayoutInnerState
} from '@/app/dashboard/layout.info'

// Route types (existing)
// ... existing route type exports ...
