// import { Monitoring } from 'react-scan/monitoring/next'
import '@repo/ui/styles/globals.css' // ! load the local stylesheets first to allow for overrides of the ui package components
import './globals.css'
// Configure server auth for declarative routing SessionPage wrappers
// This must be imported before any SessionPage is used
import '@/routes/configure-auth'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { cn } from '@repo/ui/lib/utils'
import ThemeProvider from '@repo/ui/components/theme-provider'
import ReactQueryProviders from '@/utils/providers/ReactQueryProviders'
import type { JSX } from 'react'
import AuthProviders from '@/utils/providers/AuthProviders/index'
import NextTopLoader from 'nextjs-toploader'
import Script from 'next/script'
import { validateEnvSafe } from '#/env'
import { DynamicTanstackDevTools } from '@/components/devtools/DynamicTanstackDevTools'
import { PerformanceToggle } from '@/components/dev'

const fontSans = Inter({ subsets: ['latin'], variable: '--font-sans' })

export const metadata: Metadata = {
    title: 'Create Turborepo',
    description: 'Generated by create turbo',
}

/**
 * Root Layout
 * 
 * Provides global providers and configuration. Each route group handles its own
 * navigation and layout structure:
 * 
 * - (app)/ - Pages with MainNavigation (home, showcase, etc.)
 * - (dashboard)/ - Dashboard pages with DashboardSidebar
 * - (auth)/ - Auth pages (login, etc.) - minimal layout
 * - auth/ - Auth API routes
 * 
 * This separation ensures no layout flash when navigating between different sections.
 */
export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}): JSX.Element {
    // Use safe validation to avoid build-time errors during prerendering
    // Environment variables may not be available during static generation
    const envResult = validateEnvSafe(process.env)
    const env = envResult.success ? envResult.data : null

    return (
        <html lang="en">
            <head>
                <link rel="manifest" href="/site.webmanifest" />
                <meta name="theme-color" content="#000000" />
                <link rel="apple-touch-icon" href="/icons/apple-touch-icon.png" />
                {process.env.NODE_ENV === 'development' && env?.REACT_SCAN && (
                    <Script
                        src="https://unpkg.com/react-scan/dist/auto.global.js"
                        strategy="beforeInteractive"
                        async
                    />
                )}
            </head>
            <body
                className={cn(
                    fontSans.variable,
                    'bg-background flex h-dvh w-dvw flex-col font-sans antialiased'
                )}
            >
                {process.env.NODE_ENV === 'development' &&
                    env?.REACT_SCAN &&
                    env.REACT_SCAN_TOKEN && (
                        // <Monitoring
                        //     apiKey={env.REACT_SCAN_TOKEN} // Safe to expose publically
                        //     url="https://monitoring.react-scan.com/api/v1/ingest"
                        //     commit={env.REACT_SCAN_GIT_COMMIT_HASH} // optional but recommended
                        //     branch={env.REACT_SCAN_GIT_BRANCH} // optional but recommended
                        // />
                        <></>
                    )}
                <AuthProviders>
                    <ThemeProvider
                        attribute="class"
                        defaultTheme="system"
                        enableSystem
                        disableTransitionOnChange
                    >
                        <NextTopLoader />
                        <ReactQueryProviders>
                            {children}
                            <DynamicTanstackDevTools />
                            <PerformanceToggle />
                        </ReactQueryProviders>
                    </ThemeProvider>
                </AuthProviders>
            </body>
        </html>
    )
}
