// Automatically generated by declarative-routing, do NOT edit
import { z } from "zod";
import { makeGetRoute, makeRoute } from "./makeRoute";

const defaultInfo = {
  search: z.object({})
};

import * as HomeRoute from "@/app/page.info";
import * as DashboardRoute from "@/app/(dashboard)/page.info";
import * as DashboardBuildStatsBuildTimesRoute from "@/app/(dashboard)/build-stats/build-times/page.info";
import * as DashboardBuildStatsBundleSizesRoute from "@/app/(dashboard)/build-stats/bundle-sizes/page.info";
import * as CoverageOverviewRoute from "@/app/(dashboard)/coverage/page.info";
import * as CoverageByPackageRoute from "@/app/(dashboard)/coverage/packages/page.info";
import * as CoverageTrendsRoute from "@/app/(dashboard)/coverage/trends/page.info";
import * as DashboardDocumentationRoute from "@/app/(dashboard)/documentation/page.info";
import * as DashboardPackagesDependenciesRoute from "@/app/(dashboard)/packages/dependencies/page.info";
import * as DashboardPackagesHealthRoute from "@/app/(dashboard)/packages/health/page.info";
import * as DashboardSettingsRoute from "@/app/(dashboard)/settings/page.info";
import * as DashboardTestResultsHistoryRoute from "@/app/(dashboard)/test-results/history/page.info";
import * as DashboardTestResultsLatestRoute from "@/app/(dashboard)/test-results/latest/page.info";
import * as ApiBuildStatsRoute from "@/app/api/build-stats/route.info";
import * as ApiCoverageRoute from "@/app/api/coverage/route.info";
import * as ApiPackagesRoute from "@/app/api/packages/route.info";
import * as ApiTestResultsRoute from "@/app/api/test-results/route.info";

export const Home = makeRoute(
  "/",
  {
    ...defaultInfo,
    ...HomeRoute.Route
  }
);
export const Dashboard = makeRoute(
  "/(dashboard)",
  {
    ...defaultInfo,
    ...DashboardRoute.Route
  }
);
export const DashboardBuildStatsBuildTimes = makeRoute(
  "/(dashboard)/build-stats/build-times",
  {
    ...defaultInfo,
    ...DashboardBuildStatsBuildTimesRoute.Route
  }
);
export const DashboardBuildStatsBundleSizes = makeRoute(
  "/(dashboard)/build-stats/bundle-sizes",
  {
    ...defaultInfo,
    ...DashboardBuildStatsBundleSizesRoute.Route
  }
);
export const CoverageOverview = makeRoute(
  "/(dashboard)/coverage",
  {
    ...defaultInfo,
    ...CoverageOverviewRoute.Route
  }
);
export const CoverageByPackage = makeRoute(
  "/(dashboard)/coverage/packages",
  {
    ...defaultInfo,
    ...CoverageByPackageRoute.Route
  }
);
export const CoverageTrends = makeRoute(
  "/(dashboard)/coverage/trends",
  {
    ...defaultInfo,
    ...CoverageTrendsRoute.Route
  }
);
export const DashboardDocumentation = makeRoute(
  "/(dashboard)/documentation",
  {
    ...defaultInfo,
    ...DashboardDocumentationRoute.Route
  }
);
export const DashboardPackagesDependencies = makeRoute(
  "/(dashboard)/packages/dependencies",
  {
    ...defaultInfo,
    ...DashboardPackagesDependenciesRoute.Route
  }
);
export const DashboardPackagesHealth = makeRoute(
  "/(dashboard)/packages/health",
  {
    ...defaultInfo,
    ...DashboardPackagesHealthRoute.Route
  }
);
export const DashboardSettings = makeRoute(
  "/(dashboard)/settings",
  {
    ...defaultInfo,
    ...DashboardSettingsRoute.Route
  }
);
export const DashboardTestResultsHistory = makeRoute(
  "/(dashboard)/test-results/history",
  {
    ...defaultInfo,
    ...DashboardTestResultsHistoryRoute.Route
  }
);
export const DashboardTestResultsLatest = makeRoute(
  "/(dashboard)/test-results/latest",
  {
    ...defaultInfo,
    ...DashboardTestResultsLatestRoute.Route
  }
);
export const ApiBuildStats = makeRoute(
  "/api/build-stats",
  {
    ...defaultInfo,
    ...ApiBuildStatsRoute.Route
  }
);
export const ApiPackages = makeRoute(
  "/api/packages",
  {
    ...defaultInfo,
    ...ApiPackagesRoute.Route
  }
);
export const ApiTestResults = makeRoute(
  "/api/test-results",
  {
    ...defaultInfo,
    ...ApiTestResultsRoute.Route
  }
);

export const getApiCoverage = makeGetRoute(
  "/api/coverage",
  {
    ...defaultInfo,
    ...ApiCoverageRoute.Route
  },
  ApiCoverageRoute.GET
);
