/**
 * Type for query key factory functions.
 * Each key factory returns a readonly tuple representing a query key.
 */
export type QueryKeyFactory = (...args: readonly unknown[]) => readonly unknown[];

/**
 * Type for a keys object containing query key factories.
 */
export type QueryKeys = Record<string, QueryKeyFactory>;

/**
 * Type for custom hook definitions.
 */
export type CustomHooks = Record<string, (...args: readonly unknown[]) => unknown>;

/**
 * Extract keys type from a hooks object (router or custom).
 */
export type ExtractKeys<T> = T extends { keys: infer K }
  ? K extends QueryKeys ? K : Record<string, never>
  : T extends { queryKeys: infer K }
    ? K extends QueryKeys ? K : Record<string, never>
    : Record<string, never>;

/**
 * Configuration for merging hooks.
 */
export type MergeHooksConfig<
  TRouter extends Record<string, unknown>,
  TComposite extends Record<string, unknown>,
  TCustom extends CustomHooks
> = {
  /**
   * Router hooks generated by createRouterHooks.
   * May include `queryKeys` property with key factories.
   */
  router: TRouter;

  /** Composite hooks generated by createCompositeHooks. */
  composite: TComposite;

  /**
   * Custom hooks specific to this domain.
   * May include `keys` property with key factories.
   */
  custom?: TCustom;
};

/**
 * Combined keys from all hook sources.
 */
export type MergedKeys<
  TRouter extends Record<string, unknown>,
  TCustom extends CustomHooks
> = ExtractKeys<TRouter> & ExtractKeys<TCustom>;

/**
 * Merged hooks type - combines router, composite, and custom hooks.
 * Also combines `keys` from all sources.
 */
export type MergedHooks<
  TRouter extends Record<string, unknown>,
  TComposite extends Record<string, unknown>,
  TCustom extends CustomHooks
> = Omit<TRouter, 'queryKeys' | 'keys'> &
  Omit<TComposite, 'keys'> &
  Omit<TCustom, 'keys'> & {
    keys: MergedKeys<TRouter, TCustom>;
  };

/**
 * Custom hooks with optional keys - the result type.
 */
export type CustomHooksWithKeys<
  THooks extends CustomHooks,
  TKeys extends QueryKeys = Record<string, never>
> = THooks & {
  keys: TKeys;
};

/**
 * Options for defineCustomHooks.
 */
export type DefineCustomHooksOptions<TKeys extends QueryKeys> = {
  /**
   * Query key factories for this hook domain.
   * Define all query keys that this domain "owns" or needs to reference.
   */
  keys?: TKeys;
};
